/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpAddPlus: typeof import('~icons/ep/add-plus')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    LYSUploader: typeof import('./components/LYSUploader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
